# Jekyll configuration
# Site
url: https://whitecaffemocha.github.io
title: WhiteCaffeMocha
description: Jekyll blog
timezone: Asia/Seoul
lang: ko

# Open Graph
# og_image: 
og_type: website
og_locale: ko_kr

# Google Analytics
# google_analytics: 

# Jekyll plugins
plugins:
  - jekyll-paginate

# Sass config
sass:
  style: compressed

# Markdown config
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

# Page link
permalink: /:title

# Paginate
paginate: 10
paginate_path: /:num

# Add folder to convert
collections:
  tabs:
    output: true
    sort_by: order
  category:
    output: true

# Set layout and permalink according to type
defaults:
  -
    scope:
      type: posts
    values:
      layout: page
      permalink: /:collection/:title
      page_type: post
  -
    scope:
      type: tabs
    values:
      layout: page
      permalink: /:collection/:name
  -
    scope:
      type: category
    values:
      layout: category
      permalink: /:collection/:name